import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath, URL } from 'node:url'

import { defineConfig, type Plugin } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'
import tailwindcss from '@tailwindcss/vite'
import svgLoader from 'vite-svg-loader'

// Keeps the IconName union in sync with src/assets/icons: regenerates on server
// start, build, and whenever a svg is added or removed during dev.
function iconNames(): Plugin {
  const iconsDir = fileURLToPath(new URL('./src/assets/icons', import.meta.url))
  const outFile = fileURLToPath(new URL('./src/components/ui/iconNames.ts', import.meta.url))

  function generate() {
    const names = readdirSync(iconsDir)
      .filter((file) => file.endsWith('.svg'))
      .map((file) => file.replace('.svg', ''))
      .sort()
    const union = names.length ? names.map((name) => `'${name}'`).join(' | ') : 'never'
    const content = `// AUTO-GENERATED by the iconNames plugin in vite.config.ts — do not edit by hand.
export type IconName = ${union}
`
    // skip identical writes so the dev server doesn't reload on every start
    if (existsSync(outFile) && readFileSync(outFile, 'utf8') === content) return
    writeFileSync(outFile, content)
  }

  return {
    name: 'icon-names',
    buildStart: generate,
    configureServer(server) {
      server.watcher.on('all', (event, file) => {
        if ((event === 'add' || event === 'unlink') && file.startsWith(iconsDir) && file.endsWith('.svg')) {
          generate()
        }
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueDevTools(),
    tailwindcss(),
    svgLoader(),
    iconNames(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  },
})
